// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBQMJsNkmiAsGLdbAWQOjJ71t7AunbOH4',
    appId: '1:722889361340:web:cb5fcc7d847497a8b68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    authDomain: 'newnew-1a703.firebaseapp.com',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
    measurementId: 'G-K7GQK8WHF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_5gIci-gr_Ib8gu9b76e5tU2MUYZjMio',
    appId: '1:722889361340:android:50049b74ffb95d61b68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPxWi4kB0R7K0jpBMbHBNUCvfvPWIo7xo',
    appId: '1:722889361340:ios:8e3c3ad30b54825db68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
    iosClientId: '722889361340-4qlidk68bvp75sbpagbn439t3a3llkv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPxWi4kB0R7K0jpBMbHBNUCvfvPWIo7xo',
    appId: '1:722889361340:ios:d320f7a678c7d4feb68db9',
    messagingSenderId: '722889361340',
    projectId: 'newnew-1a703',
    databaseURL: 'https://newnew-1a703-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'newnew-1a703.appspot.com',
    iosClientId: '722889361340-ncl4dfuba63ifosnq57mj9regg7cqv33.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestore.RunnerTests',
  );
}
